id: A40B844CA
title: 'The Shower of Blessings: A Prayer to the Lineage of The Sealed Quintessence,
  the Innermost Secret Guru Practice'
type: translation
pechas:
- ID0C0BBBD
- I94FF0414
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:33:57.304582
  last_modified_at: 2023-01-04 12:33:57.304595
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  ID0C0BBBD/A4FC: 42AD
  I94FF0414/91CA: 42AD
